/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAjustesRouteImport } from './routes/_authenticated/app.ajustes'
import { Route as AuthenticatedAppAuditoriaRouteImport } from './routes/_authenticated/app.auditoria'
import { Route as AuthenticatedAppDivergenciasRouteImport } from './routes/_authenticated/app.divergencias'
import { Route as AuthenticatedAppEmpresasRouteImport } from './routes/_authenticated/app.empresas'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app.usuarios'
import { Route as AuthenticatedAppCobreIndexRouteImport } from './routes/_authenticated/app.cobre.index'
import { Route as AuthenticatedAppCobreBarrasRouteImport } from './routes/_authenticated/app.cobre.barras'
import { Route as AuthenticatedAppCobreDevolucaoRouteImport } from './routes/_authenticated/app.cobre.devolucao'
import { Route as AuthenticatedAppCobreHistoricoRouteImport } from './routes/_authenticated/app.cobre.historico'
import { Route as AuthenticatedAppCobreMovimentacoesRouteImport } from './routes/_authenticated/app.cobre.movimentacoes'
import { Route as AuthenticatedAppCobrePedacosRouteImport } from './routes/_authenticated/app.cobre.pedacos'
import { Route as AuthenticatedAppCobrePesquisaRouteImport } from './routes/_authenticated/app.cobre.pesquisa'
import { Route as AuthenticatedAppCobreRelatoriosRouteImport } from './routes/_authenticated/app.cobre.relatorios'
import { Route as AuthenticatedAppCobreSaidaRouteImport } from './routes/_authenticated/app.cobre.saida'
import { Route as AuthenticatedAppContagensIndexRouteImport } from './routes/_authenticated/app.contagens.index'
import { Route as AuthenticatedAppContagensIdRouteImport } from './routes/_authenticated/app.contagens.$id'
import { Route as AuthenticatedAppContagensNovaRouteImport } from './routes/_authenticated/app.contagens.nova'
import { Route as AuthenticatedAppFerramentasIndexRouteImport } from './routes/_authenticated/app.ferramentas.index'
import { Route as AuthenticatedAppFerramentasEmprestimosRouteImport } from './routes/_authenticated/app.ferramentas.emprestimos'
import { Route as AuthenticatedAppFerramentasHistoricoRouteImport } from './routes/_authenticated/app.ferramentas.historico'
import { Route as AuthenticatedAppFerramentasListaRouteImport } from './routes/_authenticated/app.ferramentas.lista'
import { Route as AuthenticatedAppFerramentasLocalizacoesRouteImport } from './routes/_authenticated/app.ferramentas.localizacoes'
import { Route as AuthenticatedAppFerramentasPesquisaRouteImport } from './routes/_authenticated/app.ferramentas.pesquisa'
import { Route as AuthenticatedAppFerramentasRelatoriosRouteImport } from './routes/_authenticated/app.ferramentas.relatorios'
import { Route as AuthenticatedAppPatrimoniosIndexRouteImport } from './routes/_authenticated/app.patrimonios.index'
import { Route as AuthenticatedAppPatrimoniosIdRouteImport } from './routes/_authenticated/app.patrimonios.$id'
import { Route as AuthenticatedAppPatrimoniosEmprestimosRouteImport } from './routes/_authenticated/app.patrimonios.emprestimos'
import { Route as AuthenticatedAppPatrimoniosInativosRouteImport } from './routes/_authenticated/app.patrimonios.inativos'
import { Route as AuthenticatedAppPatrimoniosListaRouteImport } from './routes/_authenticated/app.patrimonios.lista'
import { Route as AuthenticatedAppPatrimoniosRelatoriosRouteImport } from './routes/_authenticated/app.patrimonios.relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAjustesRoute = AuthenticatedAppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditoriaRoute =
  AuthenticatedAppAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDivergenciasRoute =
  AuthenticatedAppDivergenciasRouteImport.update({
    id: '/divergencias',
    path: '/divergencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmpresasRoute =
  AuthenticatedAppEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreIndexRoute =
  AuthenticatedAppCobreIndexRouteImport.update({
    id: '/cobre/',
    path: '/cobre/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreBarrasRoute =
  AuthenticatedAppCobreBarrasRouteImport.update({
    id: '/cobre/barras',
    path: '/cobre/barras',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreDevolucaoRoute =
  AuthenticatedAppCobreDevolucaoRouteImport.update({
    id: '/cobre/devolucao',
    path: '/cobre/devolucao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreHistoricoRoute =
  AuthenticatedAppCobreHistoricoRouteImport.update({
    id: '/cobre/historico',
    path: '/cobre/historico',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreMovimentacoesRoute =
  AuthenticatedAppCobreMovimentacoesRouteImport.update({
    id: '/cobre/movimentacoes',
    path: '/cobre/movimentacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobrePedacosRoute =
  AuthenticatedAppCobrePedacosRouteImport.update({
    id: '/cobre/pedacos',
    path: '/cobre/pedacos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobrePesquisaRoute =
  AuthenticatedAppCobrePesquisaRouteImport.update({
    id: '/cobre/pesquisa',
    path: '/cobre/pesquisa',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreRelatoriosRoute =
  AuthenticatedAppCobreRelatoriosRouteImport.update({
    id: '/cobre/relatorios',
    path: '/cobre/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCobreSaidaRoute =
  AuthenticatedAppCobreSaidaRouteImport.update({
    id: '/cobre/saida',
    path: '/cobre/saida',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContagensIndexRoute =
  AuthenticatedAppContagensIndexRouteImport.update({
    id: '/contagens/',
    path: '/contagens/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContagensIdRoute =
  AuthenticatedAppContagensIdRouteImport.update({
    id: '/contagens/$id',
    path: '/contagens/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContagensNovaRoute =
  AuthenticatedAppContagensNovaRouteImport.update({
    id: '/contagens/nova',
    path: '/contagens/nova',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasIndexRoute =
  AuthenticatedAppFerramentasIndexRouteImport.update({
    id: '/ferramentas/',
    path: '/ferramentas/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasEmprestimosRoute =
  AuthenticatedAppFerramentasEmprestimosRouteImport.update({
    id: '/ferramentas/emprestimos',
    path: '/ferramentas/emprestimos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasHistoricoRoute =
  AuthenticatedAppFerramentasHistoricoRouteImport.update({
    id: '/ferramentas/historico',
    path: '/ferramentas/historico',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasListaRoute =
  AuthenticatedAppFerramentasListaRouteImport.update({
    id: '/ferramentas/lista',
    path: '/ferramentas/lista',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasLocalizacoesRoute =
  AuthenticatedAppFerramentasLocalizacoesRouteImport.update({
    id: '/ferramentas/localizacoes',
    path: '/ferramentas/localizacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasPesquisaRoute =
  AuthenticatedAppFerramentasPesquisaRouteImport.update({
    id: '/ferramentas/pesquisa',
    path: '/ferramentas/pesquisa',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasRelatoriosRoute =
  AuthenticatedAppFerramentasRelatoriosRouteImport.update({
    id: '/ferramentas/relatorios',
    path: '/ferramentas/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPatrimoniosIndexRoute =
  AuthenticatedAppPatrimoniosIndexRouteImport.update({
    id: '/patrimonios/',
    path: '/patrimonios/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPatrimoniosIdRoute =
  AuthenticatedAppPatrimoniosIdRouteImport.update({
    id: '/patrimonios/$id',
    path: '/patrimonios/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPatrimoniosEmprestimosRoute =
  AuthenticatedAppPatrimoniosEmprestimosRouteImport.update({
    id: '/patrimonios/emprestimos',
    path: '/patrimonios/emprestimos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPatrimoniosInativosRoute =
  AuthenticatedAppPatrimoniosInativosRouteImport.update({
    id: '/patrimonios/inativos',
    path: '/patrimonios/inativos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPatrimoniosListaRoute =
  AuthenticatedAppPatrimoniosListaRouteImport.update({
    id: '/patrimonios/lista',
    path: '/patrimonios/lista',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPatrimoniosRelatoriosRoute =
  AuthenticatedAppPatrimoniosRelatoriosRouteImport.update({
    id: '/patrimonios/relatorios',
    path: '/patrimonios/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/ajustes': typeof AuthenticatedAppAjustesRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/divergencias': typeof AuthenticatedAppDivergenciasRoute
  '/app/empresas': typeof AuthenticatedAppEmpresasRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/cobre/barras': typeof AuthenticatedAppCobreBarrasRoute
  '/app/cobre/devolucao': typeof AuthenticatedAppCobreDevolucaoRoute
  '/app/cobre/historico': typeof AuthenticatedAppCobreHistoricoRoute
  '/app/cobre/movimentacoes': typeof AuthenticatedAppCobreMovimentacoesRoute
  '/app/cobre/pedacos': typeof AuthenticatedAppCobrePedacosRoute
  '/app/cobre/pesquisa': typeof AuthenticatedAppCobrePesquisaRoute
  '/app/cobre/relatorios': typeof AuthenticatedAppCobreRelatoriosRoute
  '/app/cobre/saida': typeof AuthenticatedAppCobreSaidaRoute
  '/app/contagens/$id': typeof AuthenticatedAppContagensIdRoute
  '/app/contagens/nova': typeof AuthenticatedAppContagensNovaRoute
  '/app/ferramentas/emprestimos': typeof AuthenticatedAppFerramentasEmprestimosRoute
  '/app/ferramentas/historico': typeof AuthenticatedAppFerramentasHistoricoRoute
  '/app/ferramentas/lista': typeof AuthenticatedAppFerramentasListaRoute
  '/app/ferramentas/localizacoes': typeof AuthenticatedAppFerramentasLocalizacoesRoute
  '/app/ferramentas/pesquisa': typeof AuthenticatedAppFerramentasPesquisaRoute
  '/app/ferramentas/relatorios': typeof AuthenticatedAppFerramentasRelatoriosRoute
  '/app/patrimonios/$id': typeof AuthenticatedAppPatrimoniosIdRoute
  '/app/patrimonios/emprestimos': typeof AuthenticatedAppPatrimoniosEmprestimosRoute
  '/app/patrimonios/inativos': typeof AuthenticatedAppPatrimoniosInativosRoute
  '/app/patrimonios/lista': typeof AuthenticatedAppPatrimoniosListaRoute
  '/app/patrimonios/relatorios': typeof AuthenticatedAppPatrimoniosRelatoriosRoute
  '/app/cobre/': typeof AuthenticatedAppCobreIndexRoute
  '/app/contagens/': typeof AuthenticatedAppContagensIndexRoute
  '/app/ferramentas/': typeof AuthenticatedAppFerramentasIndexRoute
  '/app/patrimonios/': typeof AuthenticatedAppPatrimoniosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/ajustes': typeof AuthenticatedAppAjustesRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/divergencias': typeof AuthenticatedAppDivergenciasRoute
  '/app/empresas': typeof AuthenticatedAppEmpresasRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/cobre/barras': typeof AuthenticatedAppCobreBarrasRoute
  '/app/cobre/devolucao': typeof AuthenticatedAppCobreDevolucaoRoute
  '/app/cobre/historico': typeof AuthenticatedAppCobreHistoricoRoute
  '/app/cobre/movimentacoes': typeof AuthenticatedAppCobreMovimentacoesRoute
  '/app/cobre/pedacos': typeof AuthenticatedAppCobrePedacosRoute
  '/app/cobre/pesquisa': typeof AuthenticatedAppCobrePesquisaRoute
  '/app/cobre/relatorios': typeof AuthenticatedAppCobreRelatoriosRoute
  '/app/cobre/saida': typeof AuthenticatedAppCobreSaidaRoute
  '/app/contagens/$id': typeof AuthenticatedAppContagensIdRoute
  '/app/contagens/nova': typeof AuthenticatedAppContagensNovaRoute
  '/app/ferramentas/emprestimos': typeof AuthenticatedAppFerramentasEmprestimosRoute
  '/app/ferramentas/historico': typeof AuthenticatedAppFerramentasHistoricoRoute
  '/app/ferramentas/lista': typeof AuthenticatedAppFerramentasListaRoute
  '/app/ferramentas/localizacoes': typeof AuthenticatedAppFerramentasLocalizacoesRoute
  '/app/ferramentas/pesquisa': typeof AuthenticatedAppFerramentasPesquisaRoute
  '/app/ferramentas/relatorios': typeof AuthenticatedAppFerramentasRelatoriosRoute
  '/app/patrimonios/$id': typeof AuthenticatedAppPatrimoniosIdRoute
  '/app/patrimonios/emprestimos': typeof AuthenticatedAppPatrimoniosEmprestimosRoute
  '/app/patrimonios/inativos': typeof AuthenticatedAppPatrimoniosInativosRoute
  '/app/patrimonios/lista': typeof AuthenticatedAppPatrimoniosListaRoute
  '/app/patrimonios/relatorios': typeof AuthenticatedAppPatrimoniosRelatoriosRoute
  '/app/cobre': typeof AuthenticatedAppCobreIndexRoute
  '/app/contagens': typeof AuthenticatedAppContagensIndexRoute
  '/app/ferramentas': typeof AuthenticatedAppFerramentasIndexRoute
  '/app/patrimonios': typeof AuthenticatedAppPatrimoniosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/ajustes': typeof AuthenticatedAppAjustesRoute
  '/_authenticated/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/_authenticated/app/divergencias': typeof AuthenticatedAppDivergenciasRoute
  '/_authenticated/app/empresas': typeof AuthenticatedAppEmpresasRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/cobre/barras': typeof AuthenticatedAppCobreBarrasRoute
  '/_authenticated/app/cobre/devolucao': typeof AuthenticatedAppCobreDevolucaoRoute
  '/_authenticated/app/cobre/historico': typeof AuthenticatedAppCobreHistoricoRoute
  '/_authenticated/app/cobre/movimentacoes': typeof AuthenticatedAppCobreMovimentacoesRoute
  '/_authenticated/app/cobre/pedacos': typeof AuthenticatedAppCobrePedacosRoute
  '/_authenticated/app/cobre/pesquisa': typeof AuthenticatedAppCobrePesquisaRoute
  '/_authenticated/app/cobre/relatorios': typeof AuthenticatedAppCobreRelatoriosRoute
  '/_authenticated/app/cobre/saida': typeof AuthenticatedAppCobreSaidaRoute
  '/_authenticated/app/contagens/$id': typeof AuthenticatedAppContagensIdRoute
  '/_authenticated/app/contagens/nova': typeof AuthenticatedAppContagensNovaRoute
  '/_authenticated/app/ferramentas/emprestimos': typeof AuthenticatedAppFerramentasEmprestimosRoute
  '/_authenticated/app/ferramentas/historico': typeof AuthenticatedAppFerramentasHistoricoRoute
  '/_authenticated/app/ferramentas/lista': typeof AuthenticatedAppFerramentasListaRoute
  '/_authenticated/app/ferramentas/localizacoes': typeof AuthenticatedAppFerramentasLocalizacoesRoute
  '/_authenticated/app/ferramentas/pesquisa': typeof AuthenticatedAppFerramentasPesquisaRoute
  '/_authenticated/app/ferramentas/relatorios': typeof AuthenticatedAppFerramentasRelatoriosRoute
  '/_authenticated/app/patrimonios/$id': typeof AuthenticatedAppPatrimoniosIdRoute
  '/_authenticated/app/patrimonios/emprestimos': typeof AuthenticatedAppPatrimoniosEmprestimosRoute
  '/_authenticated/app/patrimonios/inativos': typeof AuthenticatedAppPatrimoniosInativosRoute
  '/_authenticated/app/patrimonios/lista': typeof AuthenticatedAppPatrimoniosListaRoute
  '/_authenticated/app/patrimonios/relatorios': typeof AuthenticatedAppPatrimoniosRelatoriosRoute
  '/_authenticated/app/cobre/': typeof AuthenticatedAppCobreIndexRoute
  '/_authenticated/app/contagens/': typeof AuthenticatedAppContagensIndexRoute
  '/_authenticated/app/ferramentas/': typeof AuthenticatedAppFerramentasIndexRoute
  '/_authenticated/app/patrimonios/': typeof AuthenticatedAppPatrimoniosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/divergencias'
    | '/app/empresas'
    | '/app/usuarios'
    | '/app/'
    | '/app/cobre/barras'
    | '/app/cobre/devolucao'
    | '/app/cobre/historico'
    | '/app/cobre/movimentacoes'
    | '/app/cobre/pedacos'
    | '/app/cobre/pesquisa'
    | '/app/cobre/relatorios'
    | '/app/cobre/saida'
    | '/app/contagens/$id'
    | '/app/contagens/nova'
    | '/app/ferramentas/emprestimos'
    | '/app/ferramentas/historico'
    | '/app/ferramentas/lista'
    | '/app/ferramentas/localizacoes'
    | '/app/ferramentas/pesquisa'
    | '/app/ferramentas/relatorios'
    | '/app/patrimonios/$id'
    | '/app/patrimonios/emprestimos'
    | '/app/patrimonios/inativos'
    | '/app/patrimonios/lista'
    | '/app/patrimonios/relatorios'
    | '/app/cobre/'
    | '/app/contagens/'
    | '/app/ferramentas/'
    | '/app/patrimonios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/ajustes'
    | '/app/auditoria'
    | '/app/divergencias'
    | '/app/empresas'
    | '/app/usuarios'
    | '/app'
    | '/app/cobre/barras'
    | '/app/cobre/devolucao'
    | '/app/cobre/historico'
    | '/app/cobre/movimentacoes'
    | '/app/cobre/pedacos'
    | '/app/cobre/pesquisa'
    | '/app/cobre/relatorios'
    | '/app/cobre/saida'
    | '/app/contagens/$id'
    | '/app/contagens/nova'
    | '/app/ferramentas/emprestimos'
    | '/app/ferramentas/historico'
    | '/app/ferramentas/lista'
    | '/app/ferramentas/localizacoes'
    | '/app/ferramentas/pesquisa'
    | '/app/ferramentas/relatorios'
    | '/app/patrimonios/$id'
    | '/app/patrimonios/emprestimos'
    | '/app/patrimonios/inativos'
    | '/app/patrimonios/lista'
    | '/app/patrimonios/relatorios'
    | '/app/cobre'
    | '/app/contagens'
    | '/app/ferramentas'
    | '/app/patrimonios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/ajustes'
    | '/_authenticated/app/auditoria'
    | '/_authenticated/app/divergencias'
    | '/_authenticated/app/empresas'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/'
    | '/_authenticated/app/cobre/barras'
    | '/_authenticated/app/cobre/devolucao'
    | '/_authenticated/app/cobre/historico'
    | '/_authenticated/app/cobre/movimentacoes'
    | '/_authenticated/app/cobre/pedacos'
    | '/_authenticated/app/cobre/pesquisa'
    | '/_authenticated/app/cobre/relatorios'
    | '/_authenticated/app/cobre/saida'
    | '/_authenticated/app/contagens/$id'
    | '/_authenticated/app/contagens/nova'
    | '/_authenticated/app/ferramentas/emprestimos'
    | '/_authenticated/app/ferramentas/historico'
    | '/_authenticated/app/ferramentas/lista'
    | '/_authenticated/app/ferramentas/localizacoes'
    | '/_authenticated/app/ferramentas/pesquisa'
    | '/_authenticated/app/ferramentas/relatorios'
    | '/_authenticated/app/patrimonios/$id'
    | '/_authenticated/app/patrimonios/emprestimos'
    | '/_authenticated/app/patrimonios/inativos'
    | '/_authenticated/app/patrimonios/lista'
    | '/_authenticated/app/patrimonios/relatorios'
    | '/_authenticated/app/cobre/'
    | '/_authenticated/app/contagens/'
    | '/_authenticated/app/ferramentas/'
    | '/_authenticated/app/patrimonios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ajustes': {
      id: '/_authenticated/app/ajustes'
      path: '/ajustes'
      fullPath: '/app/ajustes'
      preLoaderRoute: typeof AuthenticatedAppAjustesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/auditoria': {
      id: '/_authenticated/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/divergencias': {
      id: '/_authenticated/app/divergencias'
      path: '/divergencias'
      fullPath: '/app/divergencias'
      preLoaderRoute: typeof AuthenticatedAppDivergenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/empresas': {
      id: '/_authenticated/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AuthenticatedAppEmpresasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/': {
      id: '/_authenticated/app/cobre/'
      path: '/cobre'
      fullPath: '/app/cobre/'
      preLoaderRoute: typeof AuthenticatedAppCobreIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/barras': {
      id: '/_authenticated/app/cobre/barras'
      path: '/cobre/barras'
      fullPath: '/app/cobre/barras'
      preLoaderRoute: typeof AuthenticatedAppCobreBarrasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/devolucao': {
      id: '/_authenticated/app/cobre/devolucao'
      path: '/cobre/devolucao'
      fullPath: '/app/cobre/devolucao'
      preLoaderRoute: typeof AuthenticatedAppCobreDevolucaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/historico': {
      id: '/_authenticated/app/cobre/historico'
      path: '/cobre/historico'
      fullPath: '/app/cobre/historico'
      preLoaderRoute: typeof AuthenticatedAppCobreHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/movimentacoes': {
      id: '/_authenticated/app/cobre/movimentacoes'
      path: '/cobre/movimentacoes'
      fullPath: '/app/cobre/movimentacoes'
      preLoaderRoute: typeof AuthenticatedAppCobreMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/pedacos': {
      id: '/_authenticated/app/cobre/pedacos'
      path: '/cobre/pedacos'
      fullPath: '/app/cobre/pedacos'
      preLoaderRoute: typeof AuthenticatedAppCobrePedacosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/pesquisa': {
      id: '/_authenticated/app/cobre/pesquisa'
      path: '/cobre/pesquisa'
      fullPath: '/app/cobre/pesquisa'
      preLoaderRoute: typeof AuthenticatedAppCobrePesquisaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/relatorios': {
      id: '/_authenticated/app/cobre/relatorios'
      path: '/cobre/relatorios'
      fullPath: '/app/cobre/relatorios'
      preLoaderRoute: typeof AuthenticatedAppCobreRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cobre/saida': {
      id: '/_authenticated/app/cobre/saida'
      path: '/cobre/saida'
      fullPath: '/app/cobre/saida'
      preLoaderRoute: typeof AuthenticatedAppCobreSaidaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contagens/': {
      id: '/_authenticated/app/contagens/'
      path: '/contagens'
      fullPath: '/app/contagens/'
      preLoaderRoute: typeof AuthenticatedAppContagensIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contagens/$id': {
      id: '/_authenticated/app/contagens/$id'
      path: '/contagens/$id'
      fullPath: '/app/contagens/$id'
      preLoaderRoute: typeof AuthenticatedAppContagensIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contagens/nova': {
      id: '/_authenticated/app/contagens/nova'
      path: '/contagens/nova'
      fullPath: '/app/contagens/nova'
      preLoaderRoute: typeof AuthenticatedAppContagensNovaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/': {
      id: '/_authenticated/app/ferramentas/'
      path: '/ferramentas'
      fullPath: '/app/ferramentas/'
      preLoaderRoute: typeof AuthenticatedAppFerramentasIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/emprestimos': {
      id: '/_authenticated/app/ferramentas/emprestimos'
      path: '/ferramentas/emprestimos'
      fullPath: '/app/ferramentas/emprestimos'
      preLoaderRoute: typeof AuthenticatedAppFerramentasEmprestimosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/historico': {
      id: '/_authenticated/app/ferramentas/historico'
      path: '/ferramentas/historico'
      fullPath: '/app/ferramentas/historico'
      preLoaderRoute: typeof AuthenticatedAppFerramentasHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/lista': {
      id: '/_authenticated/app/ferramentas/lista'
      path: '/ferramentas/lista'
      fullPath: '/app/ferramentas/lista'
      preLoaderRoute: typeof AuthenticatedAppFerramentasListaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/localizacoes': {
      id: '/_authenticated/app/ferramentas/localizacoes'
      path: '/ferramentas/localizacoes'
      fullPath: '/app/ferramentas/localizacoes'
      preLoaderRoute: typeof AuthenticatedAppFerramentasLocalizacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/pesquisa': {
      id: '/_authenticated/app/ferramentas/pesquisa'
      path: '/ferramentas/pesquisa'
      fullPath: '/app/ferramentas/pesquisa'
      preLoaderRoute: typeof AuthenticatedAppFerramentasPesquisaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas/relatorios': {
      id: '/_authenticated/app/ferramentas/relatorios'
      path: '/ferramentas/relatorios'
      fullPath: '/app/ferramentas/relatorios'
      preLoaderRoute: typeof AuthenticatedAppFerramentasRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/patrimonios/': {
      id: '/_authenticated/app/patrimonios/'
      path: '/patrimonios'
      fullPath: '/app/patrimonios/'
      preLoaderRoute: typeof AuthenticatedAppPatrimoniosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/patrimonios/$id': {
      id: '/_authenticated/app/patrimonios/$id'
      path: '/patrimonios/$id'
      fullPath: '/app/patrimonios/$id'
      preLoaderRoute: typeof AuthenticatedAppPatrimoniosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/patrimonios/emprestimos': {
      id: '/_authenticated/app/patrimonios/emprestimos'
      path: '/patrimonios/emprestimos'
      fullPath: '/app/patrimonios/emprestimos'
      preLoaderRoute: typeof AuthenticatedAppPatrimoniosEmprestimosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/patrimonios/inativos': {
      id: '/_authenticated/app/patrimonios/inativos'
      path: '/patrimonios/inativos'
      fullPath: '/app/patrimonios/inativos'
      preLoaderRoute: typeof AuthenticatedAppPatrimoniosInativosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/patrimonios/lista': {
      id: '/_authenticated/app/patrimonios/lista'
      path: '/patrimonios/lista'
      fullPath: '/app/patrimonios/lista'
      preLoaderRoute: typeof AuthenticatedAppPatrimoniosListaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/patrimonios/relatorios': {
      id: '/_authenticated/app/patrimonios/relatorios'
      path: '/patrimonios/relatorios'
      fullPath: '/app/patrimonios/relatorios'
      preLoaderRoute: typeof AuthenticatedAppPatrimoniosRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAjustesRoute: typeof AuthenticatedAppAjustesRoute
  AuthenticatedAppAuditoriaRoute: typeof AuthenticatedAppAuditoriaRoute
  AuthenticatedAppDivergenciasRoute: typeof AuthenticatedAppDivergenciasRoute
  AuthenticatedAppEmpresasRoute: typeof AuthenticatedAppEmpresasRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCobreBarrasRoute: typeof AuthenticatedAppCobreBarrasRoute
  AuthenticatedAppCobreDevolucaoRoute: typeof AuthenticatedAppCobreDevolucaoRoute
  AuthenticatedAppCobreHistoricoRoute: typeof AuthenticatedAppCobreHistoricoRoute
  AuthenticatedAppCobreMovimentacoesRoute: typeof AuthenticatedAppCobreMovimentacoesRoute
  AuthenticatedAppCobrePedacosRoute: typeof AuthenticatedAppCobrePedacosRoute
  AuthenticatedAppCobrePesquisaRoute: typeof AuthenticatedAppCobrePesquisaRoute
  AuthenticatedAppCobreRelatoriosRoute: typeof AuthenticatedAppCobreRelatoriosRoute
  AuthenticatedAppCobreSaidaRoute: typeof AuthenticatedAppCobreSaidaRoute
  AuthenticatedAppContagensIdRoute: typeof AuthenticatedAppContagensIdRoute
  AuthenticatedAppContagensNovaRoute: typeof AuthenticatedAppContagensNovaRoute
  AuthenticatedAppFerramentasEmprestimosRoute: typeof AuthenticatedAppFerramentasEmprestimosRoute
  AuthenticatedAppFerramentasHistoricoRoute: typeof AuthenticatedAppFerramentasHistoricoRoute
  AuthenticatedAppFerramentasListaRoute: typeof AuthenticatedAppFerramentasListaRoute
  AuthenticatedAppFerramentasLocalizacoesRoute: typeof AuthenticatedAppFerramentasLocalizacoesRoute
  AuthenticatedAppFerramentasPesquisaRoute: typeof AuthenticatedAppFerramentasPesquisaRoute
  AuthenticatedAppFerramentasRelatoriosRoute: typeof AuthenticatedAppFerramentasRelatoriosRoute
  AuthenticatedAppPatrimoniosIdRoute: typeof AuthenticatedAppPatrimoniosIdRoute
  AuthenticatedAppPatrimoniosEmprestimosRoute: typeof AuthenticatedAppPatrimoniosEmprestimosRoute
  AuthenticatedAppPatrimoniosInativosRoute: typeof AuthenticatedAppPatrimoniosInativosRoute
  AuthenticatedAppPatrimoniosListaRoute: typeof AuthenticatedAppPatrimoniosListaRoute
  AuthenticatedAppPatrimoniosRelatoriosRoute: typeof AuthenticatedAppPatrimoniosRelatoriosRoute
  AuthenticatedAppCobreIndexRoute: typeof AuthenticatedAppCobreIndexRoute
  AuthenticatedAppContagensIndexRoute: typeof AuthenticatedAppContagensIndexRoute
  AuthenticatedAppFerramentasIndexRoute: typeof AuthenticatedAppFerramentasIndexRoute
  AuthenticatedAppPatrimoniosIndexRoute: typeof AuthenticatedAppPatrimoniosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAjustesRoute: AuthenticatedAppAjustesRoute,
  AuthenticatedAppAuditoriaRoute: AuthenticatedAppAuditoriaRoute,
  AuthenticatedAppDivergenciasRoute: AuthenticatedAppDivergenciasRoute,
  AuthenticatedAppEmpresasRoute: AuthenticatedAppEmpresasRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCobreBarrasRoute: AuthenticatedAppCobreBarrasRoute,
  AuthenticatedAppCobreDevolucaoRoute: AuthenticatedAppCobreDevolucaoRoute,
  AuthenticatedAppCobreHistoricoRoute: AuthenticatedAppCobreHistoricoRoute,
  AuthenticatedAppCobreMovimentacoesRoute:
    AuthenticatedAppCobreMovimentacoesRoute,
  AuthenticatedAppCobrePedacosRoute: AuthenticatedAppCobrePedacosRoute,
  AuthenticatedAppCobrePesquisaRoute: AuthenticatedAppCobrePesquisaRoute,
  AuthenticatedAppCobreRelatoriosRoute: AuthenticatedAppCobreRelatoriosRoute,
  AuthenticatedAppCobreSaidaRoute: AuthenticatedAppCobreSaidaRoute,
  AuthenticatedAppContagensIdRoute: AuthenticatedAppContagensIdRoute,
  AuthenticatedAppContagensNovaRoute: AuthenticatedAppContagensNovaRoute,
  AuthenticatedAppFerramentasEmprestimosRoute:
    AuthenticatedAppFerramentasEmprestimosRoute,
  AuthenticatedAppFerramentasHistoricoRoute:
    AuthenticatedAppFerramentasHistoricoRoute,
  AuthenticatedAppFerramentasListaRoute: AuthenticatedAppFerramentasListaRoute,
  AuthenticatedAppFerramentasLocalizacoesRoute:
    AuthenticatedAppFerramentasLocalizacoesRoute,
  AuthenticatedAppFerramentasPesquisaRoute:
    AuthenticatedAppFerramentasPesquisaRoute,
  AuthenticatedAppFerramentasRelatoriosRoute:
    AuthenticatedAppFerramentasRelatoriosRoute,
  AuthenticatedAppPatrimoniosIdRoute: AuthenticatedAppPatrimoniosIdRoute,
  AuthenticatedAppPatrimoniosEmprestimosRoute:
    AuthenticatedAppPatrimoniosEmprestimosRoute,
  AuthenticatedAppPatrimoniosInativosRoute:
    AuthenticatedAppPatrimoniosInativosRoute,
  AuthenticatedAppPatrimoniosListaRoute: AuthenticatedAppPatrimoniosListaRoute,
  AuthenticatedAppPatrimoniosRelatoriosRoute:
    AuthenticatedAppPatrimoniosRelatoriosRoute,
  AuthenticatedAppCobreIndexRoute: AuthenticatedAppCobreIndexRoute,
  AuthenticatedAppContagensIndexRoute: AuthenticatedAppContagensIndexRoute,
  AuthenticatedAppFerramentasIndexRoute: AuthenticatedAppFerramentasIndexRoute,
  AuthenticatedAppPatrimoniosIndexRoute: AuthenticatedAppPatrimoniosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
